---
- name: Install java and net-tools
  hosts: nexues_servers
  tasks:

    - name: Install Java
      apt: name=openjdk-8-jre-headless
       
    - name: Install net-tools
      apt: name=net-tools

- name: Download and unpack nexus Installer
  hosts: nexues_servers
  tasks:
    - name: Download nexus intsller
      get_url:
        url: https://download.sonatype.com/nexus/3/nexus-3.89.1-02-linux-x86_64.tar.gz
        dest: /opt/
      register: download_result
    - name: Unpck the nexus intsaller
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists 
    - name: Find nexus folder
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - name: Check if nexus folder exists
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Rename nexus directory
      shell: mv {{find_result.files[0].path}} /opt/nexus      
      when: not stat_result.stat.exists 


- name: Create nexus user to own nexus folder
  hosts: nexues_servers
  tasks:
    - name: Ensure  group nexus exist
      group:
        name: nexus
        state: present
    - name: Create nexus user
      user:
        name: nexus
        group: nexus 
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start nexus with nexus user
  hosts: nexues_servers
  become: True
  become_user: nexus 
  tasks:
    - name: Set run_as_user nexus
      copy:
        content: | 
          run_as_user="nexus"
        dest: /opt/nexus/bin/nexus.rc
    - name: Start nexus
      command: /opt/nexus/bin/nexus start

- name: Verify nexus running
  hosts: nexues_servers
  tasks:
    - name: Ensure that the app is running
      shell: ps aux | grep  nexus
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
    - name: Wait a minute untile the port open
      pause:
        minutes: 1
    - name: Ensure that the app is running
      shell: netstat -lntp 
      register: app_status

    - debug: msg={{app_status.stdout_lines}}
  